project:
  type: website
  output-dir: docs

website:
  title: "Math and rambling"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DarpanGanatra
      - icon: twitter
        href: https://twitter.com/DarpanGanatra
format:
  html:
    toc: true
    theme: litera
    highlight-style: a11y
    css: styles.css
    code-line-numbers: true
