project:
  type: website
  output-dir: docs

website:
  title: "Math and rambling"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DarpanGanatra
      - icon: twitter
        href: https://twitter.com/DarpanGanatra
format:
  html:
    theme: sandstorm
    css: styles.css
